#!/usr/bin/env python

import h5py

height = 2
width  = 3
dShape = (height, width) 


with h5py.File("test.cci", "w") as f:
    f.attrs["type"]   = "composablechannelimage"
    f.attrs["dims"]  = dShape 
    f.attrs["version"] = "1.0"

    layers = f.create_group("layers") 

    # create a layer
    l = layers.create_group("0000")

    m = l.create_dataset("mask", shape=dShape, data=[[0, 1, 0], [0, 1, 0]])

    t = l.create_dataset("temperature", shape=dShape, data=[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]])
    t.attrs["globalrange"] = [0.0, 52.0] 

    p = l.create_dataset("pressure", shape=dShape, data=[[6.0, 7.0, 8.0], [9.0, 10.0, 11.0]])
    p.attrs["globalrange"] = [-1.0, 25.3]

