#!/usr/bin/env python

import sys
import h5py

if len(sys.argv) > 1:
    infile = sys.argv[1]
else:
    print("no file input arg ... exiting")
    exit(0)

with h5py.File(infile, "r") as f:
    for a in f.attrs:
        print("{}: {}".format(a, f.attrs[a]))

    print("images:")
    for i in f["images"]:
        print("  image: {}".format(i))

        print("    layers:")
        for l in f["images"][i]["layers"]:
            print("      layer: {}".format(l))
            for a in f["images"][i]["layers"][l].attrs:
                print("        {}: {}".format(a, f["images"][i]["layers"][l].attrs[a]))

            print("        channels:")
            for c in f["images"][i]["layers"][l]["channels"]:
                print("          {}".format(c))
                for a in f["images"][i]["layers"][l]["channels"][c].attrs:
                    print("            {}: {}".format(a, f["images"][i]["layers"][l]["channels"][c].attrs[a]))
