#!/usr/bin/env python

import sys
import h5py

if len(sys.argv) > 1:
    infile = sys.argv[1]
else:
    print("no file input arg ... exiting")
    exit(0)

def get_image_names(source):
    results = []
    for i in f["images"]:
        results.append(i)
    return results 

def get_layer_names(source, image):
    results = []
    for i in f["images"][image]["layers"]:
        results.append(i)
    return results 

def get_channel_names(source, image, layer):
    results = []
    for i in f["images"][image]["layers"][layer]["channels"]:
        results.append(i)
    return results 

def get_full_image_from_channel(dims, channel, offset):
    im   = numpy.zeros(dims)
    mask = numpy.zeros(dims)

    i = 0
    j = 0
    for x in range(offset[0], dims[0]):
        for y in range(offset[1], dims[1]):
            im[x][y]   = channel[i][j]
            mask[x][y] = 1
            j = j + 1 
        i = i + 1 

    return im

with h5py.File(infile, "r") as f:

    for im in get_image_names(f):
        print("image: {}".format(im))
        for layer in get_layer_names(f, im):
            print("  layer: {}".format(layer))
            for ch in get_channel_names(f, im, layer):
                print("    channel: {}".format(ch))

        print("{}.png".format(im))
