#!/usr/bin/env python

import h5py
import numpy

im_height = 50
im_width  = 100
im_shape = (im_height, im_width) 

shape = [(10, 10),
         (10, 15),
         (10, 20)]

offsets = {} 
offsets["0000"] = ( 0, 0)
offsets["0001"] = (10, 10)
offsets["0002"] = (20, 20)

ranges = [
          (0.0, 10.0),
          (10.0, 20.0),
          (20.0, 30.0)
         ]

im_names = ["0000"]
layer_names = ["0000", "0001", "0002"] 

def add_channel(channels, name, dims, minmax):

    values = numpy.random.uniform( minmax[0], minmax[1], dims) 
    c = channels.create_dataset(name, shape=dims, data=values)
    # print(c)
    # print(values)

    return

def create_layer(layers, name, shape):
    global ranges
    global offsets

    # create a layer
    l = layers.create_group(name)
    l.attrs["offset"] = offsets[name]
    l.attrs["dims"]   = shape 

    # create channels
    c = l.create_group("channels")

    add_channel(c, "temperature", shape, ranges[0]) 
    add_channel(c, "density",     shape, ranges[1]) 
    add_channel(c, "pressure",    shape, ranges[2]) 


with h5py.File("compose.cis", "w") as f:
    f.attrs["class"]   = "composablechannelimage"
    f.attrs["dims"]  = im_shape 
    f.attrs["version"] = "1.0"

    images = f.create_group("images") 

    # create an image
    for name in im_names:
        image  = images.create_group(name)
        layers = image.create_group("layers") 
        for i in range(len(layer_names)): 
            create_layer(layers, layer_names[i], shape[i])

